#!/usr/bin/env python

# ==========================================================
# Author: https://github.com/sevaho
# Repo: https://github.com/sevaho/scripts
#
# ==========================================================

import sys

key = sys.argv[1]

print(key)
crc = int(key[-2:])
assert 97 - (int(key[:-2]) % 97) == crc, f"No mod97 nr:" + key
